services:
  - type: web
    name: cavaliver-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: RENDER
        value: true
    autoDeploy: true
    disk:
      name: database
      mountPath: /etc/render/database
      sizeGB: 1
