services:
  - type: web
    name: cavaliver-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: sh render_start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
