services:
  - type: web
    name: cavaliver-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash render_start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: development
      - key: FLASK_DEBUG
        value: "1"
      - key: SECRET_KEY
        value: "une_cle_secrete_longue_et_complexe_pour_production"
    autoDeploy: true
    disk:
      name: database
      mountPath: /etc/render/database
      sizeGB: 1
