"""Ajout des colonnes etapes_depart et etapes_arrivee au modele Prestation

Revision ID: 4fc0f385122c
Revises: 
Create Date: 2025-04-19 02:23:36.184122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc0f385122c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etapes_depart', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('etapes_arrivee', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestation', schema=None) as batch_op:
        batch_op.drop_column('etapes_arrivee')
        batch_op.drop_column('etapes_depart')

    # ### end Alembic commands ###
